apiVersion: v1
kind: Template
metadata:
  name: compliance-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: compliance
    spec:
      envName: ${ENV_NAME}
      title: Compliance
      deploymentRepo: https://github.com/RedHatInsights/compliance-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/compliance
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        image: 'quay.io/cloudservices/compliance-frontend:bdde349'
  module:
    manifestLocation: /apps/compliance/fed-mods.json
    modules:
      - id: compliance
        module: ./RootApp
        routes:
          - pathname: /insights/compliance
  navItems:
    - expandable: true
      routes:
        - appId: compliance
          href: /insights/compliance/report
          product: Red Hat Insights
          title: Reports
        - appId: compliance
          href: /insights/compliance/scappolicies
          product: Red Hat Insights
          title: SCAP Policies
        - appId: compliance
          href: /insights/compliance/systems
          product: Red Hat Insights
          title: Systems
      title: Compliance
  title: Compliance
      module:
        manifestLocation: "/apps/compliance/fed-mods.json"
        modules:
          - id: "compliance"
            module: "./RootApp"
            routes:
              - pathname: /insights/compliance

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/compliance-frontend
